[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
game_record1 = "H47FW1ucEfv2zr1ET4VMCnFDkc7eB2D9pfUrKL6WLKYF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
